on: 
  push:
    paths-ignore:
      - 'cli/**'

name: verify cli

jobs:
  verify_cli:
    name: verify cli
    runs-on: self-hosted
    steps:
      - name: test
        run: |
          echo "No build required"
          echo $date > date.txt

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: date
          path: date.txt

  build_cli:
    name: build cli
    needs: [verify_cli]
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required" '
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: date
      - name: test
        run: |
          cat date.txt
