jobs:
  test0:
    runs-on: 8c8g
    container: golang:1.18.0
    steps:
    - uses: actions/checkout@v2

    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.6.1'
    - run: go version
    - run: go build .
name: test

on:
  push:
    branches:
    - main
